apiVersion: v1
kind: ConfigMap
metadata:
  name: farming-assistant-config
  namespace: ai-crop-recommendation
data:
  DATABASE_URL: "sqlite:////data/farming_assistant.db"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
